// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGscZ0RPxM1s3sqWdYYdUnVgvA83A8dGA',
    appId: '1:400327307442:android:6a751c2619a6dd2587d9ab',
    messagingSenderId: '400327307442',
    projectId: 'ybox-tv-ml82p',
    storageBucket: 'ybox-tv-ml82p.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE2u6u57CmyR5Gum21Z3r5P3ROTuzzncE',
    appId: '1:400327307442:ios:4fcbcaa4f49693a087d9ab',
    messagingSenderId: '400327307442',
    projectId: 'ybox-tv-ml82p',
    storageBucket: 'ybox-tv-ml82p.firebasestorage.app',
    iosBundleId: 'tv.ybox.yboxAdmin',
  );

  // Desktop (Windows) and web both authenticate with the project's Web app
  // credentials — same project, same Firestore data, no per-platform app
  // needed.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ_1U2q9O5_4H9MUsjMwMRCrGvfDZOeC8',
    appId: '1:400327307442:web:58f07d9737402dd787d9ab',
    messagingSenderId: '400327307442',
    projectId: 'ybox-tv-ml82p',
    authDomain: 'ybox-tv-ml82p.firebaseapp.com',
    storageBucket: 'ybox-tv-ml82p.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ_1U2q9O5_4H9MUsjMwMRCrGvfDZOeC8',
    appId: '1:400327307442:web:58f07d9737402dd787d9ab',
    messagingSenderId: '400327307442',
    projectId: 'ybox-tv-ml82p',
    authDomain: 'ybox-tv-ml82p.firebaseapp.com',
    storageBucket: 'ybox-tv-ml82p.firebasestorage.app',
  );
}
